"""empty message

Revision ID: 61ca06c6b0c7
Revises: a2722acc2c81
Create Date: 2022-08-23 18:31:39.128838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61ca06c6b0c7'
down_revision = 'a2722acc2c81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('seeking_description', sa.String(length=400), nullable=True))
    op.add_column('venue', sa.Column('website_link', sa.String(length=400), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'website_link')
    op.drop_column('venue', 'seeking_description')
    # ### end Alembic commands ###
