"""empty message

Revision ID: a2722acc2c81
Revises: 70aa0b0bc37b
Create Date: 2022-08-23 18:28:29.127273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2722acc2c81'
down_revision = '70aa0b0bc37b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('genres', sa.String(), nullable=True))
    op.add_column('venue', sa.Column('seeking_talent', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'seeking_talent')
    op.drop_column('venue', 'genres')
    # ### end Alembic commands ###
